language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
      env: COVERAGE=1
env:
  global:
    - secure: S8QheEMVpSRsPPIhYQZ4tUCTbxpM7csZ0GydJaPY8p/FAEnZLiH6xcsiTGKOljva5HDelCdBvunaWtUO/+CdKIgsdbQGbqc1aWmG6gr+ShQk4X3KzeAA91AFmkJOR6Jv69lUTm6Uo9AKs1JtuVZsOa1aoOmfApohqFuXsRBNXlg=

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organisation: cps-it

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

before_script:
  - composer install --no-progress

script:
  - >
    if [[ "$COVERAGE" != "1" ]]; then
      echo;
      echo "Running unit tests";
      .build/bin/phpunit --colors tests/Unit/
    fi

  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .build/bin/phpunit --colors -c tests/Build/UnitTests.xml tests/Unit/
      rm -rf .build/vendor/ .build/bin/
      sonar-scanner -Dproject.settings=sonar-project.properties
    fi
