<?php

declare(strict_types=1);

namespace CPSIT\Auditor\Generator;

/***************************************************************
 *  Copyright notice
 *
 *  (c) 2018 Dirk Wenzel <wenzel@cps-it.de>
 *  All rights reserved
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the text file GPL.txt and important notices to the license
 * from the author is found in LICENSE.txt distributed with these scripts.
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

use Composer\Composer;
use Composer\IO\IOInterface;
use CPSIT\Auditor\Reflection\InstallPath;
use CPSIT\Auditor\SettingsInterface as SI;

/**
 * Class BundleDescriberClassGenerator
 */
class BundleDescriberClassGenerator
{
    public const MESSAGE_INFO_LEAD = '<info>' . SI::PACKAGE_IDENTIFIER . '</info> :';
    public const ERROR_ROOT_PACKAGE_NOT_FOUND = ' Package not found (probably scheduled for removal); generation of application reflection class skipped.';
    public const MESSAGE_GENERATE_BUNDLE_DESCRIBER = ' Generate bundle describer class...';
    public const MESSAGE_DONE_BUNDLE_DESCRIBER = ' bundle describer class generated';

    private static string $generatedClassTemplate = <<<'PHP'
<?php

declare(strict_types=1);

namespace CPSIT\Auditor;

/**
 * This class is generated by cpsit/auditor, specifically by
 * @see \Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
%s implements DescriberInterface
{
    use PropertiesTrait;
    protected static string $properties = '%s';
    protected static string $installedPackages = '%s';

    private function __construct()
    {
    }
}

PHP;

    protected InstallPath $installPath;

    protected IOInterface $io;

    public function __construct(Composer $composer, IOInterface $io)
    {
        $this->installPath = new InstallPath($composer);
        $this->io = $io;
    }

    public function writeFile(array $properties = [], array $installedPackages = []): void
    {
        $filePath = $this->getFilePath();


        if (!file_exists(dirname($filePath))) {
            $this->io->write(self::MESSAGE_INFO_LEAD . self::ERROR_ROOT_PACKAGE_NOT_FOUND);
            return;
        }

        file_put_contents($filePath, $this->generateSource($properties, $installedPackages));
        chmod($filePath, 0664);

        $this->io->write(self::MESSAGE_INFO_LEAD . self::MESSAGE_DONE_BUNDLE_DESCRIBER);
    }

    /**
     * Generates the source for the BundleDescriber class
     */
    protected function generateSource(array $properties, array $installedPackages): string
    {
        return sprintf(
            self::$generatedClassTemplate,
            'fin' . 'al ' . 'cla' . 'ss ' . SI::BUNDLE_DESCRIBER_CLASS, // note: workaround for regex-based code parsers :-(
            addcslashes(serialize($properties), "'"),
            addcslashes(serialize($installedPackages), "'")
        );
    }

    /**
     * Get the path of the Application Reflection Class
     */
    protected function getFilePath(): string
    {
        return $this->installPath->toString() . '/'
            . SI::SOURCE_FOLDER_NAME . '/' . SI::BUNDLE_DESCRIBER_CLASS . '.php';
    }

}
