<?php

namespace Cpsit\Conductor;

/**
 * This class is generated by cpsit/conductor, specifically by
 * @see \Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class ApplicationReflection
{
    const ROOT_PACKAGE_NAME = 'cpsit/ihkof-bundle';

    private function __construct()
    {
    }
}
