<?php

namespace CPSIT\Auditor;

/**
 * This class is generated by cpsit/auditor, specifically by
 * @see \Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class BundleDescriber implements DescriberInterface
{
    static protected $properties = array (
  'aliases' =>
  array (
  ),
  'minimumStability' => 'stable',
  'stabilityFlags' =>
  array (
    'cpsit/auditor' => 20,
  ),
  'references' =>
  array (
  ),
  'preferStable' => false,
  'config' =>
  array (
  ),
  'scripts' =>
  array (
  ),
  'repositories' =>
  array (
    0 =>
    array (
      'type' => 'vcs',
      'url' => 'git@github.com:CPS-IT/auditor.git',
    ),
    'packagist.org' =>
    array (
      'type' => 'composer',
      'url' => 'https?://repo.packagist.org',
      'allow_ssl_downgrade' => true,
    ),
  ),
  'license' =>
  array (
  ),
  'keywords' => NULL,
  'description' => 'Test project bundle for auditor composer plugin',
  'homepage' => NULL,
  'authors' =>
  array (
    0 =>
    array (
      'name' => 'Dirk Wenzel',
      'email' => 'der-wenzel@gmx.de',
    ),
  ),
  'support' =>
  array (
  ),
  'name' => 'dwenzel/auditor-bundle',
  'prettyName' => 'dwenzel/auditor-bundle',
  'names' =>
  array (
    0 => 'dwenzel/auditor-bundle',
  ),
  'id' => -1,
  'type' => 'project',
  'targetDir' => NULL,
  'extra' =>
  array (
  ),
  'installationSource' => NULL,
  'sourceType' => '',
  'sourceUrl' => '',
  'sourceReference' => 'e2913039bdf51542e9ca5db07bf334bd7abe0421',
  'sourceMirrors' => NULL,
  'distType' => '',
  'distUrl' => '',
  'distUrls' =>
  array (
  ),
  'distReference' => 'e2913039bdf51542e9ca5db07bf334bd7abe0421',
  'distSha1Checksum' => NULL,
  'distMirrors' => NULL,
  'version' => 'dev-develop',
  'fullPrettyVersion' => 'dev-develop',
  'releaseDate' => NULL,
  'conflicts' =>
  array (
  ),
  'provides' =>
  array (
  ),
  'replaces' =>
  array (
  ),
  'suggests' =>
  array (
  ),
  'autoload' =>
  array (
  ),
  'devAutoload' =>
  array (
  ),
  'includePaths' =>
  array (
  ),
  'repository' => NULL,
  'uniqueName' => 'dwenzel/auditor-bundle-dev-develop',
  'notificationUrl' => NULL,
);

    private function __construct()
    {
    }

    public static function getProperty(string $key) {
        if (!isset (self::$properties[$key])) {
            throw new \OutOfBoundsException(
                'Required key "' . $key . '" is not valid: property not found in package'
            );
        }
    }
}
